[package]
name = "wyzoid"
version = "0.1.0"
authors = ["Maël <contact@maeln.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.13"
