[package]
name = "wyzoid"
version = "0.1.0"
authors = ["Maël <contact@maeln.com>"]
edition = "2018"
license = "CECILL-2.1"
readme = "README.md"
repository = "https://github.com/maeln/wyzoid"


[profile.release]
opt-level = 3
debug = true
lto = true

[dependencies]
rand = "0.7"
ash = "0.29"
